/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     RKPSIrSensor
  * - <b>Project file</b>:     C:/ti/Bortnikov/workspace_v7/RKPS_RML_IR_Sense/Application/SensorControl/IR_Sensor.scp
  * - <b>Code prefix</b>:      -
  * - <b>Operating system</b>: TI-RTOS
  * - <b>Tool version</b>:     2.0.0.324
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC1310, revision -, package QFN32 5x5 RHB
  * - <b>Created</b>:          2018-07-24 16:58:51.114
  * - <b>Computer</b>:         ELESTA-25
  * - <b>User</b>:             Vladimir Bortnikov
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * No description entered
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - IrSensor:
  *     - <b>A: Ain thermosensor</b>: DIO13
  *     - <b>A: BATTERY voltage ADC IN</b>: DIO7
  *     - <b>A: To ADC from PIR 2048 aka 0</b>: DIO12
  *     - <b>O: Key for termistor devider</b>: DIO14
  *     - <b>O: PIR on pin On by 0</b>: DIO4
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_ir_sensor IrSensor
  * No description entered
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     RKPSIrSensor
  * - <b>Code prefix</b>:      -
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  * - Hooks for run-time logging
  *
  * @{
  */
#ifndef SCIF_H
#define SCIF_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_tirtos.h"


/// Target chip name
#define SCIF_TARGET_CHIP_NAME_CC1310
/// Target chip package
#define SCIF_TARGET_CHIP_PACKAGE_QFN32_5X5_RHB

/// Number of tasks implemented by this driver
#define SCIF_TASK_COUNT 1

/// IrSensor: Task ID
#define SCIF_IR_SENSOR_TASK_ID 0


/// IrSensor I/O mapping: Ain thermosensor
#define SCIF_IR_SENSOR_DIO_A_TEMPERAT 13
/// IrSensor I/O mapping: BATTERY voltage ADC IN
#define SCIF_IR_SENSOR_DIO_A_BATTERY 7
/// IrSensor I/O mapping: To ADC from PIR 2048 aka 0
#define SCIF_IR_SENSOR_DIO_A_PIR_AIN 12
/// IrSensor I/O mapping: Key for termistor devider
#define SCIF_IR_SENSOR_DIO_O_BT_P_ON 14
/// IrSensor I/O mapping: PIR on pin On by 0
#define SCIF_IR_SENSOR_DIO_O_PIR_ON 4


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// IrSensor: Task configuration structure
typedef struct {
    uint16_t lineHigh; ///< 
    uint16_t lineLow;  ///< 
} SCIF_IR_SENSOR_CFG_T;


/// IrSensor: Task input data structure
typedef struct {
    uint16_t isLedIndication; ///< system armed or disarmed
    uint16_t isPirControl;    ///< 
    uint16_t lightLine;       ///< 
} SCIF_IR_SENSOR_INPUT_T;


/// IrSensor: Task output data structure
typedef struct {
    uint16_t battery;     ///< battery adc value
    uint16_t forMcuEvent; ///< 
    uint16_t thermo;      ///< ADC value for thermistor delvider
} SCIF_IR_SENSOR_OUTPUT_T;


/// IrSensor: Task state structure
typedef struct {
    uint16_t alarmState;  ///< Sensor state if 0 then NO alarm, else ALARM
    uint16_t lastAlState; ///< the last alarm state
    uint16_t ledAdc;      ///< ledRed adc value light
    uint16_t pirAdc;      ///< 
    uint16_t timeCount;   ///< last hall2 state
    uint16_t wait;        ///< 
} SCIF_IR_SENSOR_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_IR_SENSOR_CFG_T cfg;
        SCIF_IR_SENSOR_INPUT_T input;
        SCIF_IR_SENSOR_OUTPUT_T output;
        SCIF_IR_SENSOR_STATE_T state;
    } irSensor;
} SCIF_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifTaskData    (*((volatile SCIF_TASK_DATA_T*) 0x400E00EA))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifReinitTaskIo(uint32_t bvTaskIds);


// RTC-based tick generation control
void scifStartRtcTicks(uint32_t tickStart, uint32_t tickPeriod);
void scifStartRtcTicksNow(uint32_t tickPeriod);
void scifStopRtcTicks(void);


#endif
//@}


// Generated by ELESTA-25 at 2018-07-24 16:58:51.114
